/**
 * Notification links are generated by the database from fixed routes and
 * checked there (user_notifications_link_check). The UI checks them again
 * before navigating: anything else falls back to /notifications.
 */
const SAFE_LINK = /^\/(requisitions\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|receipts|dashboard|notifications)$/;

export function isSafeNotificationLink(link: unknown): link is string {
  return typeof link === "string" && SAFE_LINK.test(link);
}

export function safeNotificationLink(link: unknown): string {
  return isSafeNotificationLink(link) ? link : "/notifications";
}
